name: Cypress Tests

on:
  pull_request:
    branches: "main"
    paths:
      - "**.ts"
      - "**.tsx"
      - "**.js"

jobs:
  cypress-run:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 20
          cache: "npm"
      - name: Run E2E tests
        uses: cypress-io/github-action@v6
        with:
          build: npm run build
          start: npm start
      - name: Run component tests
        uses: cypress-io/github-action@v6
        with:
          install: false
          component: true
